Jumpstart.config = Jumpstart::Configuration.new({"application_name" => "hakhel",
 "business_name" => "Hakhel, LLC",
 "business_address" => "29 Ela St.\n" + "Kfar Vradim, Israel",
 "domain" => "hakhel.me",
 "support_email" => "david@odeca.net",
 "default_from_email" => "hakhel <no-reply@hakhel.me>",
 "background_job_processor" => "sidekiq",
 "email_provider" => "sendgrid",
 "account_types" => "both",
 "apns" => false,
 "fcm" => false,
 "integrations" => [],
 "omniauth_providers" => [],
 "payment_processors" => [],
 "multitenancy" => [],
 "gems" => ["acts_as_tenant"]})
